language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
  depth: false

jobs:
  include:
    - &test-stage
      stage: test
      name: Checking standards
      php: 7.1
      script:
        - php vendor/bin/phpcs --standard=PSR1 ./packages --ignore=*/spec/*
        - php vendor/bin/phpcs --standard=PSR2 ./packages --ignore=*/spec/*
        - php vendor/bin/phpstan analyse ./packages --level max
    - <<: *test-stage
      php: 7.2
    - <<: *test-stage
      php: 7.3
    - stage: split
      name: Split for repositories
      php: 7.1
      script: |
        if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" ]]; then
          vendor/bin/monorepo-builder split -v
        fi

stages:
  - test
  - name: split
    if: branch = master

install:
  -  composer install